Collect trx output and process

diff --git a/.github/workflows/ci-build.yml b/.github/workflows/ci-build.yml
--- a/.github/workflows/ci-build.yml
+++ b/.github/workflows/ci-build.yml
@@ -116,7 +116,7 @@ jobs:
       run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIG }} /p:"Platform=${{ env.BUILD_PLATFORM }}" /p:"Version=${{ needs.setup.outputs.product_version }}" /p:"AssemblyVersion=${{ needs.setup.outputs.assembly_version }}"
 
     - name: Test
-      run: dotnet test --no-restore --no-build --configuration ${{ env.BUILD_CONFIG }} --verbosity normal --collect:"XPlat Code Coverage"
+      run: dotnet test --no-restore --no-build --configuration ${{ env.BUILD_CONFIG }} --verbosity normal --logger:trx;LogFileName=TestOutput.trx --collect:"XPlat Code Coverage"
 
     - name: Code Coverage Report
       uses: irongut/CodeCoverageSummary@v1.3.0
@@ -137,9 +137,17 @@ jobs:
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         comment-title: 'Unit Test Results'
-        results-path: ./TestResults/*.trx
+        results-path: "**/*.trx"
         coverage-path: "**/coverage.cobertura.xml"
         coverage-threshold: ${{ env.COVERAGE_WARNING_THRESHOLD }}
+
+    - uses: actions/upload-artifact@v4  # upload test results
+      if: success() || failure()        # run this step even if previous step failed
+      with:
+        name: test-results
+        badge-title: Test Results
+        path: "**/*.trx"
+        reporter: dotnet-trx
 
     - name: Pull Request - Add Coverage Comment
       uses: marocchino/sticky-pull-request-comment@v2
